### PR TITLE
Change default Dataset URL - remove tailing slash

### PR DESCRIPTION
**Pull request by lutzwillek-tomtom**
[9579](https://support.dataset.com/hc/en-us/requests/9579): 

- change default Dataset URL, not including the tailing / anymore
- Reason is that when creating new datasources in Grafana using the "[scalyr-grafana-datasource-plugin](https://github.com/scalyr/scalyr-grafana-datasource-plugin)" the health check fails, in case of a taling slash.
- old (already existing) datasources seem not affected.

### CODE REVIEW

**Comment by jmakar-s1** [comment]
Thanks for submitting this.  It's been a little while since I worked on this project, what health check is failing?

Also it looks like there is are some warnings associated with unrelated code, I will push a change to master shortly (that will need to be merged into this PR before it can be merged).

**Comment by jmakar-s1** [comment]
@lutzwillek-tomtom Could you merge master into your PR branch?  Want this [this change](https://github.com/scalyr/scalyr-grafana-datasource-plugin/pull/132) to get the Github actions to complete successfully.  Once that's done I'll approve and merge the PR.

After that is done, I will also make a new release so the change can be deployed.

**Comment by lutzwillek-tomtom** [comment]
[like]  Lutz Willek reacted to your message:
________________________________

**Comment by lutzwillek-tomtom** [comment]
👍🏼 done @jmakar-s1 

> @lutzwillek-tomtom Could you merge master into your PR branch? Want [this change](https://github.com/scalyr/scalyr-grafana-datasource-plugin/pull/132) to get the Github actions to complete successfully. Once that's done I'll approve and merge the PR.
> 
> After that is done, I will also make a new release so the change can be deployed.

**Comment by jmakar-s1** [comment]
@lutzwillek-tomtom New release is now available: https://github.com/scalyr/scalyr-grafana-datasource-plugin/releases/tag/3.1.4

It doesn't look like we are still publishing to the Grafana marketplace so the new plugin release can be installed manually instead.

**Comment by lutzwillek-tomtom** [comment]
> It doesn't look like we are still publishing to the Grafana marketplace so the new plugin release can be installed manually instead.

I am aware. But this is another story, and something to solve for another day, and another customer request [9581](https://support.dataset.com/hc/en-us/requests/9581).

Back to the issue here: I tested fine (using local plugin installation) and Grafana OSS `v11.4.0 (b58701869e)`. Here is how I tested:

```
docker run -d -p 3000:3000 --name=grafana  grafana/grafana-oss
docker stop grafana
wget https://github.com/scalyr/scalyr-grafana-datasource-plugin/releases/download/3.1.4/sentinelone-dataset-datasource-3.1.4.zip
docker cp sentinelone-dataset-datasource grafana:/var/lib/grafana/plugins/
docker start grafana
```

Result:

test
version

Thanks @jmakar-s1 👍🏼

**Pull request merged**
